pipeline:
  npm-audit:
    image: node:12
    commands:
      - npm audit --production --audit-level=moderate
    when:
      event: push

  image_to_quay:
    image: docker:19
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t server-$${DRONE_COMMIT_SHA} .
      - docker build -f Dockerfile-alerts -t alerts-$${DRONE_COMMIT_SHA} .
      - docker build -f Dockerfile-lookup -t lookup-$${DRONE_COMMIT_SHA} .
      - docker login -u="ukhomeofficedigital+modern_slavery_bot" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag server-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/modern-slavery-data-service:server-$${DRONE_COMMIT_SHA}
      - docker tag alerts-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/modern-slavery-data-service:alerts-$${DRONE_COMMIT_SHA}
      - docker tag alerts-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/modern-slavery-data-service:lookup-$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:server-$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:alerts-$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/modern-slavery-data-service:lookup-$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
