pipeline:
  npm-audit:
    group: test
    image: node:12
    commands:
      - npm audit --production --audit-level=moderate
    when:
      event: push

  image_to_quay_server:
    group: tag
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    registry: quay.io
    branch: master
    repo: quay.io/ukhomeofficedigital/modern-slavery-data-service
    tags:
      - server-${DRONE_COMMIT_SHA}
      - server-build-${DRONE_BUILD_NUMBER}
      - server-latest
    when:
      branch: master
      event: push

  image_to_quay_alerts:
    group: tag
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    registry: quay.io
    branch: master
    repo: quay.io/ukhomeofficedigital/modern-slavery-data-service
    dockerfile: Dockerfile-alerts
    tags:
      - alerts-${DRONE_COMMIT_SHA}
      - alerts-build-${DRONE_BUILD_NUMBER}
      - alerts-latest
    when:
      branch: master
      event: push

  image_to_quay_migrations:
    group: tag
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+modern_slavery_bot
    registry: quay.io
    branch: master
    repo: quay.io/ukhomeofficedigital/modern-slavery-data-service
    dockerfile: Dockerfile-migraions
    tags:
      - migrations-${DRONE_COMMIT_SHA}
      - migrations-build-${DRONE_BUILD_NUMBER}
      - migrations-latest
    when:
      branch: master
      event: push

  # trigger_deploy_to_dev:
  #   image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
  #   drone_server: https://drone-gitlab.acp.homeoffice.gov.uk
  #   repo: modern-slavery/kube-modern-slavery
  #   secrets:
  #     - drone_token
  #   branch: master
  #   deploy_to: dev
  #   params: "DATA_SERVICE_VERSION=${DRONE_COMMIT_SHA}"
  #   when:
  #     branch: master
  #     event: push
